#ifndef __INVISOX_COMMON_H__
#define __INVISOX_COMMON_H__

#define QSZ(e) e.toUtf8().data()

#define _INVISOX_SHARED_MEM_NAME "invisoxSharedMem"
#define _INVISOX_SHARED_EVENT_NAME "invisoxSharedEvent"
#define _INVISOX_SHARED_MEM_SIZE 1024

#define _INVISOX_SHARED_MEM_KEY_INDEX		0
#define _INVISOX_SHARED_MEM_MOUES_INDEX		128

#define _INVISOX_EXIT_CODE_HOOING 0x93

#define _INVISOX_KF_SHIFT		0x01
#define _INVISOX_KF_ALT			0x02
#define _INVISOX_KF_CTRL		0x04

#define _INVISOX_EVENT_TYPE_KEY				0
#define _INVISOX_EVENT_TYPE_MOUSE			1

#define _INVISOX_EVENT_ACTION_KEYDOWN		0
#define _INVISOX_EVENT_ACTION_KEYUP			1
#define _INVISOX_EVENT_ACTION_LBDOWN		2
#define _INVISOX_EVENT_ACTION_LBUP			3
#define _INVISOX_EVENT_ACTION_RBDOWN		4
#define _INVISOX_EVENT_ACTION_RBUP			5
#define _INVISOX_EVENT_ACTION_MOUSEMOVE		6

#define _INVISOX_DEFAULT_EVENT_DURATION		50
#endif
